version: '3'

services:
  mail:
    container_name: mail
    build:
      context: .
      args:
        - DOMAIN=${DOMAIN}
        - HOST=${HOST}
    restart: unless-stopped
    ports:
      - "125:25"
    env_file: .env